---
title: "03_A2_model_fitting"
author: "Adam Hanbury-Brown"
date: "11/1/2022"
output: html_document
---

```{r setup, include=FALSE}
source("01_clean_A2.R")
```

Check histogram of response variable.
```{r}
hist(grouped_df$RRI_end)
```


A2 results
```{r}
modData <- grouped_df %>% 
  #filter(recoveryTime > 20) %>%
  mutate(across(where(is.numeric),scale_this)) 

mod <- gam(formula = RRI_end ~ 
             recoveryTime + 
             s(x, y, bs = "gp", k = 75, m = 2) +
             mediumReburns +
             burnSev +
             s(TmaxHist, k = 15) +
             s(adj_fold_northness, k = 15) +
             s(postFireSAP, k = 15) +
             s(postFirePrecip, k = 15),
           data = modData)

#model results
summary(mod)
plot(mod)
paste0("AIC:",AIC(mod))
```

#Check model assumptions.

Check residuals
```{r}
gam.check(mod)
```

Check concurvity
```{r}
print(concurvity(mod, full = F))
```


Check spatial autocorrelation. This is good.
```{r}
#check spatial autocorrelation
pixel.dists <- as.matrix(dist(cbind(modData$x, modData$y)))
pixel.dists.inv <- 1/pixel.dists
diag(pixel.dists.inv) <- 0
print(Moran.I(residuals(mod),pixel.dists.inv))
```

Check colinearity among predictors
```{r}
#for correlation matrix
otherVars.x <- c("recoveryTime","mediumReburns","lowReburns","x","y","RRI_end")
topoVar.x  <- c("adj_fold_northness")
histClimateVars.x <- c("TmaxHist")
seedVars.x <- c("burnSev","postFireSAP","postFirePlanting")
postFireWeather.x <- c("postFirePrecip")
predictors.x <- c(otherVars.x,topoVar.x,histClimateVars.x,seedVars.x,postFireWeather.x)
getCorrelationMatrix(d = modData, varsForCorr = predictors.x)
```

